### ISSUE TITLE
tips how to debug errors in marshalling.clj?

### ISSUE THREAD

**Issue by gonewest818** [dgrnbrg/clj-mesos#6]
Hello -  I've got a fork of this project with the dependencies modified to mesos 0.26.0 and clojure 1.7.0, and a framework using edpaget/mesos-template as a starting point also modified to mesos 0.26.0. However when I try to run this framework (so far I've tried this only in the repl) I get a NoClassDefFoundError like this:

```
Dec 29, 2015 5:43:19 AM clojure.tools.logging$eval1450$fn__1454 invoke
SEVERE: Error in registered
java.lang.NoClassDefFoundError: Could not initialize class clj_mesos.marshalling$proto__GT_map$iter__2757__2761$fn__2762
    at clj_mesos.marshalling$proto__GT_map$iter__2757__2761.invoke(marshalling.clj:78)
    at clj_mesos.marshalling$proto__GT_map.invoke(marshalling.clj:78)
    at my_mesos_framework.scheduler$scheduler$fn__3777.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler.proxy$java.lang.Object$Scheduler$7a16741e.registered(Unknown Source)

Dec 29, 2015 5:43:19 AM clojure.tools.logging$eval1450$fn__1454 invoke
SEVERE: Error in resourceOffers
java.lang.NoClassDefFoundError: Could not initialize class clj_mesos.marshalling$proto__GT_map$iter__2757__2761$fn__2762
    at clj_mesos.marshalling$proto__GT_map$iter__2757__2761.invoke(marshalling.clj:78)
    at clj_mesos.marshalling$proto__GT_map.invoke(marshalling.clj:78)
    at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
    at clojure.core.protocols$iter_reduce.invoke(protocols.clj:49)
    at clojure.core.protocols$fn__6510.invoke(protocols.clj:112)
    at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6519)
    at clojure.core$mapv.invoke(core.clj:6616)
    at my_mesos_framework.scheduler$scheduler$fn__3734$fn__3735.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler$scheduler$fn__3734.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler.proxy$java.lang.Object$Scheduler$7a16741e.resourceOffers(Unknown Source)
```

At which point I'm afraid I'm out of my depth. Any suggestions how to debug from here? I realize 0.26.0 may not be a priority for you and frankly 0.26.0 supports the Mesos HTTP API. But I feel compelled to at least understand what's happening here before I change tactics...  thanks

**Comment by gonewest818** [comment]
Actually, I reviewed the transcript again. That was the second attempt to launch the framework in that repl. The first one failed like this:

```
user=> (start)
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@716: Client environment:host.name=f5459fdc6a13
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.12-boot2docker
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Tue Nov 3 06:03:36 UTC 2015
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@log_env@753: Client environment:user.dir=/work
2015-12-29 16:02:06,064:784(0x7f44a30b3700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=zk:2181 sessionTimeout=10000 watche#<SystemMap>
r=0x7f44a9e41d00 sessionId=0 sessionPasswd=<null> context=0x7f44b8000aa0 flags=0
2015-12-29 16:02:06,065:784(0x7f4492ffd700):ZOO_INFO@check_events@1703: initiated connection to server [172.17.0.2:2181]
I1229 16:02:06.064694   811 sched.cpp:166] Version: 0.26.0
2015-12-29 16:02:06,076:784(0x7f4492ffd700):ZOO_INFO@check_events@1750: session establishment complete on server [172.17.0.2:2181], sessionId=0x151ee7402f50005, negotiated timeout=10000
I1229 16:02:06.076575   901 group.cpp:331] Group process (group(1)@172.17.0.5:51578) connected to ZooKeeper
I1229 16:02:06.076596   901 group.cpp:805] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1229 16:02:06.076604   901 group.cpp:403] Trying to create path '/mesos' in ZooKeeper
I1229 16:02:06.079354   901 detector.cpp:156] Detected a new leader: (id='4')
I1229 16:02:06.079423   901 group.cpp:674] Trying to get '/mesos/json.info_0000000004' in ZooKeeper
I1229 16:02:06.080500   901 detector.cpp:482] A new leading master (UPID=master@172.17.0.3:5050) is detected
I1229 16:02:06.080552   901 sched.cpp:264] New master detected at master@172.17.0.3:5050
I1229 16:02:06.080749   901 sched.cpp:274] No credentials provided. Attempting to register without authentication
I1229 16:02:06.084215   901 sched.cpp:643] Framework registered with 34936baf-59d4-4958-a1c2-b290bc7a3e12-0002
user=> Dec 29, 2015 4:02:06 PM clojure.tools.logging$eval1450$fn__1454 invoke
SEVERE: Error in registered
java.lang.ExceptionInInitializerError
    at clj_mesos.marshalling$proto__GT_map$iter__2757__2761.invoke(marshalling.clj:78)
    at clj_mesos.marshalling$proto__GT_map.invoke(marshalling.clj:78)
    at my_mesos_framework.scheduler$scheduler$fn__2279.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler.proxy$java.lang.Object$Scheduler$7a16741e.registered(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com/google/protobuf/ByteString
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at clojure.lang.RT.classForName(RT.java:2154)
    at clojure.lang.RT.classForName(RT.java:2163)
    at clj_mesos.marshalling$proto__GT_map$iter__2757__2761$fn__2762.<clinit>(marshalling.clj:78)
    ... 4 more

Dec 29, 2015 4:02:06 PM clojure.tools.logging$eval1450$fn__1454 invoke
SEVERE: Error in resourceOffers
java.lang.NoClassDefFoundError: Could not initialize class clj_mesos.marshalling$proto__GT_map$iter__2757__2761$fn__2762
    at clj_mesos.marshalling$proto__GT_map$iter__2757__2761.invoke(marshalling.clj:78)
    at clj_mesos.marshalling$proto__GT_map.invoke(marshalling.clj:78)
    at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
    at clojure.core.protocols$iter_reduce.invoke(protocols.clj:49)
    at clojure.core.protocols$fn__6510.invoke(protocols.clj:112)
    at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6519)
    at clojure.core$mapv.invoke(core.clj:6616)
    at my_mesos_framework.scheduler$scheduler$fn__2236$fn__2237.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler$scheduler$fn__2236.invoke(scheduler.clj:47)
    at my_mesos_framework.scheduler.proxy$java.lang.Object$Scheduler$7a16741e.resourceOffers(Unknown Source)
```

at the center of which is `Caused by: java.lang.ClassNotFoundException: com/google/protobuf/ByteString`  and this is where I am confused.  Immediately after this error I can definitely inspect that class via reflection:

```
user=> (reflect com.google.protobuf.ByteString)
{:bases #{java.lang.Object java.lang.Iterable}, :flags #{:public :abstract}, :members #{#clojure.reflect.Method{:name toString, :return-type java.lang.String, :declaring-class com.google.protobuf.ByteString, :parameter-types [], :exception-types [], :flags #{:public}} 
... etc
```

**Comment by dgrnbrg** [comment]
I will be able to assist you next week--I'm currently out of the country
without a laptop.

**Comment by gonewest818** [comment]
Thank you, and safe travels!

**Comment by gonewest818** [comment]
Hi, if you do still have a chance to help I would appreciate it.  I'm just not seeing what the issue is.

**Comment by dgrnbrg** [comment]
So, I have a few ideas, but I'll need your help to narrow it down:

One possibility is that the Mesos callbacks are trying to invoke certain
parts of Clojure. I've noticed that the way class loading interacts with
the native thread originating in Mesos--some classes don't seem to be
found. Try wrapping the callback logic in a future or async/go block to see
whether it's simply a problem that the Mesos callback thread isn't setting
the correct contextclassloader.

If that doesn't fix it, can you show me more of the code?

**Comment by gonewest818** [comment]
Absolutely, and I can post the code to github and send you the link.

Although… I should say this is nothing but a toy “hello world” type framework based on 

https://github.com/edpaget/mesos-template https://github.com/edpaget/mesos-template

so for example the callback for registered does nothing at all.

**Comment by dgrnbrg** [comment]
That'd be great--also, can you tell me your Java -version?

**Comment by gonewest818** [comment]
1.7.0

**Comment by gonewest818** [comment]
Whoops. Ignore - that's the clojure version.

**Comment by gonewest818** [comment]
This is running in Ubuntu 14.04

```
# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by gonewest818** [comment]
Ok, here are steps to reproduce.  First, you need docker, which in my case means using docker-machine on my macintosh:

```
$ docker-machine create -d virtualbox mesos-vm
$ eval "$(docker-machine env mesos-vm)"
```

then start a mesos dev environment on that 

```
$ git clone https://github.com/gonewest818/compose-mesos.git
$ cd compose-mesos
$ ./go.sh
```

then start the framework's container

```
$ cd ..
$ git clone https://github.com/gonewest818/my-mesos-framework.git
$ cd my-mesos-framework
$ docker-compose up
framework_1 | Hit CTRL+C
framework_1 | Hit CTRL+C
... 
```

which at the moment doesn't actually start the framework. But you can now enter the container namespace and launch a repl yourself

```
$ docker ps            # get the container id for the framework's container
$ docker exec -it <container_id> bash
root@63c8b3f57361:/work# lein repl
nREPL server started on port 37497 on host 127.0.0.1 - nrepl://127.0.0.1:37497
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_91-b02
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
user=>
```

and from the repl, launch the framework

```
user=> (go)
```

and that should throw the exception as reported earlier in this ticket.

**Comment by gonewest818** [comment]
I also did a quick test with Oracle Java 1.8u66 but that made no difference.

Also, because the first callback to throw the exception is "registered" I went ahead and commented that callback out entirely. When I ran the next time, the class not found exception was thrown instead by whatever next callback got invoked (in this case I think it was resourceOffers).  So it seems to me, whenever the proxy returned by make-proxy-body actually needs to invoke something.

**Comment by dgrnbrg** [comment]
Well, I noticed that your `:docker {:image "busybox"}` should just be
`:docker "busybox"` (elide fields for single-element structs so that
`XxxID` doesn't become a burden).

**Comment by gonewest818** [comment]
I noticed I can also reproduce this with the tiny example in the comment at the bottom of clj-mesos.scheduler.

```
(def myscheduler (scheduler (registered [driver fid mi]
                                        (println "registered" fid mi)) 
                            (resourceOffers [driver offers] (clojure.pprint/pprint offers))))
(def overdriver
  (driver
    myscheduler {:user "" :name "testframework"} "localhost:5050"))
(start overdriver)
```

**Comment by dgrnbrg** [comment]
Could you make a repository that I could clone to reproduce with that
example?

**Comment by gonewest818** [comment]
Sure.

```
$ git clone https://github.com/gonewest818/clj-mesos-overdriver.git
$ cd clj-mesos-overdriver
$ lein run
```

As mentioned earlier, I have a separate fork of clj-mesos with the mesos version bumped to 0.26.0.  So for completeness I left a git submodule in "checkouts", but that's up to you if you want to use it.

```
$ git submodule init
$ git submodule update
$ cd checkouts/clj-mesos
```

**Comment by dgrnbrg** [comment]
I've determined that there's some incompatibility between Clojure 1.7 and clj-mesos. I've made a separate issue to fix that. in the meantime, can you use Clojure 1.6?

**Comment by gonewest818** [comment]
ok, will do.
